server:
  port: 8799
  
spring:
  application:
    name: eureka-example
  cloud:
    config:
      enabled: false
# tag::configuration-eureka[]
eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management.security.enabled: false
# end::configuration-eureka[]

# tag::configuration-ui-hystrix[]
#spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
# end::configuration-ui-hystrix[]

# tag::configuration-ui-turbine[]
#spring.boot.admin.turbine:
#  clusters: default
#  location: turbine  #<1>
# end::configuration-ui-turbine[]

